//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationKursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KURSACHEntities : DbContext
    {
        private static KURSACHEntities _context;
        public static KURSACHEntities GetContext()
        {
            if (_context == null)
                _context = new KURSACHEntities();
            return _context;
        }
        public KURSACHEntities()
            : base("name=KURSACHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album_description> Album_description { get; set; }
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Performers> Performers { get; set; }
        public virtual DbSet<Performers_and_Albums> Performers_and_Albums { get; set; }
        public virtual DbSet<Playlist_description> Playlist_description { get; set; }
        public virtual DbSet<Playlists> Playlists { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<PlaylistDataGrid> PlaylistDataGrid { get; set; }
        public virtual DbSet<SongsDataGrid> SongsDataGrid { get; set; }
        public virtual DbSet<SongsInAlbumsDataGrid> SongsInAlbumsDataGrid { get; set; }
        public virtual DbSet<SongsInPlaylistsDataGrid> SongsInPlaylistsDataGrid { get; set; }
    }
}
