//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationKursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsInPlaylistsDataGrid
    {
        public string Name { get; set; }
        public string SongName { get; set; }
        public int Obedience { get; set; }
        public byte[] Cover { get; set; }
        public string PerformersName { get; set; }
        public byte[] song_file { get; set; }
    }
}
